### ISSUE TITLE
[Bug]: Installation error when following CONTRIBUTING.md - "invalid decimal literal"

### ISSUE THREAD

**Issue by JTarakRam** [refuel-ai/autolabel#342]
**Describe the bug**
**SyntaxError: invalid decimal literal**, 
*(base) Taraks-MacBook-Air:autolabel tarakram$ python -c "from autolabel import LabelingAgent"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tarakram/miniconda3/lib/python3.10/site-packages/autolabel/__init__.py", line 1, in <module>
    from .labeler import LabelingAgent
  File "/Users/tarakram/miniconda3/lib/python3.10/site-packages/autolabel/labeler.py", line 12, in <module>
    from autolabel.cache import SQLAlchemyCache
  File "/Users/tarakram/miniconda3/lib/python3.10/site-packages/autolabel/cache/__init__.py", line 1, in <module>
    from .base import BaseCache
  File "/Users/tarakram/miniconda3/lib/python3.10/site-packages/autolabel/cache/base.py", line 5, in <module>
    from autolabel.schema import CacheEntry
  File "/Users/tarakram/miniconda3/lib/python3.10/site-packages/autolabel/schema.py", line 10, in <module>
    from langchain.schema import Generation
  File "/Users/tarakram/miniconda3/lib/python3.10/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/Users/tarakram/miniconda3/lib/python3.10/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/Users/tarakram/miniconda3/lib/python3.10/site-packages/langchain/agents/agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "/Users/tarakram/miniconda3/lib/python3.10/site-packages/langchain/agents/tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "/Users/tarakram/miniconda3/lib/python3.10/site-packages/langchain/tools/__init__.py", line 21, in <module>
    from langchain.tools.gmail import (
  File "/Users/tarakram/miniconda3/lib/python3.10/site-packages/langchain/tools/gmail/__init__.py", line 3, in <module>
    from langchain.tools.gmail.create_draft import GmailCreateDraft
  File "/Users/tarakram/miniconda3/lib/python3.10/site-packages/langchain/tools/gmail/create_draft.py", line 11, in <module>
    from langchain.tools.gmail.base import GmailBaseTool
  File "/Users/tarakram/miniconda3/lib/python3.10/site-packages/langchain/tools/gmail/base.py", line 17, in <module>
    from googleapiclient.discovery import Resource
  File "/Users/tarakram/miniconda3/lib/python3.10/site-packages/googleapiclient/discovery.py", line 332
    return 0L*

This is the complete error when I run this --> python -c "from autolabel import LabelingAgent"

OS-
Macos

versions - 
Python 3.10.10
langchain==0.0.202
google-api-python-client==1.3

**Screenshots**
<img width="888" alt="Screenshot 2023-06-17 at 11 43 59 AM" src="https://github.com/refuel-ai/autolabel/assets/98701588/4eb394a8-c30d-48a7-83c0-197fc95fa8d8">

**Additional context**
in Setting Up Your Environment - 4 steps are successful, but got some dependency issues for numpy and scipy, we can fix them no problem, but I was getting error here - If the following code snippet does not return any error, the installation is successful:
```bash
python -c "from autolabel import LabelingAgent"
```

**Comment by rishabh-bhargava** [comment]
Thanks for reporting this @JTarakRam. I was able to follow the steps in CONTRIBUTING.md successfully in a fresh virtual environment: https://drive.google.com/file/d/1EKIZ5NUBICOF4zp-A5mJU6A65maCfzat/view?usp=sharing

Seems like in the fresh environment, we don't have `google-api-python-client` installed. 

[This](https://github.com/hwchase17/langchain/blob/master/langchain/tools/gmail/utils.py#L12), in `langchain` is where the error seems to be originating. 

One way to fix/move forward might be try this in a fresh environment. Will also investigate what happens when installing the google client package and some other threads.

**Comment by rishabh-bhargava** [comment]
Okay, if I install `google-api-python-client` with:
```bash
pip install google-api-python-client==1.3
```

and then run: `python -c "from autolabel import LabelingAgent"`, I get:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/rishabhbhargava/.pyenv/versions/install-bug/lib/python3.8/site-packages/autolabel/__init__.py", line 1, in <module>
    from .labeler import LabelingAgent
  File "/Users/rishabhbhargava/.pyenv/versions/install-bug/lib/python3.8/site-packages/autolabel/labeler.py", line 12, in <module>
    from autolabel.cache import SQLAlchemyCache
  File "/Users/rishabhbhargava/.pyenv/versions/install-bug/lib/python3.8/site-packages/autolabel/cache/__init__.py", line 1, in <module>
    from .base import BaseCache
  File "/Users/rishabhbhargava/.pyenv/versions/install-bug/lib/python3.8/site-packages/autolabel/cache/base.py", line 5, in <module>
    from autolabel.schema import CacheEntry
  File "/Users/rishabhbhargava/.pyenv/versions/install-bug/lib/python3.8/site-packages/autolabel/schema.py", line 10, in <module>
    from langchain.schema import Generation
  File "/Users/rishabhbhargava/.pyenv/versions/install-bug/lib/python3.8/site-packages/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/Users/rishabhbhargava/.pyenv/versions/install-bug/lib/python3.8/site-packages/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/Users/rishabhbhargava/.pyenv/versions/install-bug/lib/python3.8/site-packages/langchain/agents/agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "/Users/rishabhbhargava/.pyenv/versions/install-bug/lib/python3.8/site-packages/langchain/agents/tools.py", line 8, in <module>
    from langchain.tools.base import BaseTool, Tool, tool
  File "/Users/rishabhbhargava/.pyenv/versions/install-bug/lib/python3.8/site-packages/langchain/tools/__init__.py", line 21, in <module>
    from langchain.tools.gmail import (
  File "/Users/rishabhbhargava/.pyenv/versions/install-bug/lib/python3.8/site-packages/langchain/tools/gmail/__init__.py", line 3, in <module>
    from langchain.tools.gmail.create_draft import GmailCreateDraft
  File "/Users/rishabhbhargava/.pyenv/versions/install-bug/lib/python3.8/site-packages/langchain/tools/gmail/create_draft.py", line 11, in <module>
    from langchain.tools.gmail.base import GmailBaseTool
  File "/Users/rishabhbhargava/.pyenv/versions/install-bug/lib/python3.8/site-packages/langchain/tools/gmail/base.py", line 17, in <module>
    from googleapiclient.discovery import Resource
  File "/Users/rishabhbhargava/.pyenv/versions/install-bug/lib/python3.8/site-packages/googleapiclient/discovery.py", line 208
    except ValueError, e:
                     ^
SyntaxError: invalid syntax
```

It's not quite the same error, but pointing in the same direction.

**Comment by rishabh-bhargava** [comment]
@JTarakRam I believe your error is because `google-api-python-client==1.3` doesn't support Python 3.x, as can be seen here: https://github.com/googleapis/google-api-python-client/tree/v1.3#python-version

Updating this library should fix this issue. If you run:
```
pip install --upgrade  google-api-python-client
```
or (for the latest version as of today)
```
pip install google-api-python-client==2.89.0
```

And then run:
```
python -c "from autolabel import LabelingAgent"
```

This should work. Let me know if this still causes problems!

**Comment by JTarakRam** [comment]
yeah, It works perfect !! thanks

**Comment by rejuvyesh** [comment]
@rishabh-bhargava you should update the minimum required version appropriately in `pyproject.toml`

**Comment by rishabh-bhargava** [comment]
> @rishabh-bhargava you should update the minimum required version appropriately in `pyproject.toml`

@rejuvyesh - `google-api-python-client` is actually not part of `autolabel`. Since it was installed before using `autolabel`, it's hard to set any requirements on it. Curious if you have any suggestions on this!

**Comment by rejuvyesh** [comment]
Ah, I thought you were depending on it via one of your dependencies. Never mind then.

**Comment by rishabh-bhargava** [comment]
Will be closing this issue since it's resolved! cc: @JTarakRam
