### ISSUE TITLE
[Bug]: compute_confidence with multi-class label task results in RecursionError

### ISSUE THREAD

**Issue by suz4n99** [refuel-ai/autolabel#644]
**Describe the bug**
When I use multilabel_classification, set compute_confidence to True und try to save the agent.run instance via the save function, I receive a recursion error (RecursionError: maximum recursion depth exceeded while calling a Python object)

**To Reproduce**
A list of steps to reproduce the behavior:
I tried to follow your twitter emotions tutorial (https://github.com/refuel-ai/autolabel/blob/3e5509859fb907c0aa147d412cb1ea75be348de4/examples/twitter_emotion_detection/example_twitter_emotion_detection.ipynb). I used the refuel-llm as my model.
My goal was to label the seed.csv file. For this, I used the following config code:
```
config = {
    "task_name": "EmotionClassification",
    "task_type": "multilabel_classification",
    "dataset": {"label_column": "labels", "label_separator": ", ", "delimiter": ","},
    "model": {"provider": "refuel", "name": "refuel-llm"},
    "prompt": {
        "task_guidelines": "You are an expert at classifying tweets as neutral or one or more of the given emotions that best represent the mental state of the poster.\nYour job is to correctly label the provided input example into one or more of the following categories:\n{labels}",
        "output_guidelines": 'You will return the answer as a comma separated list of labels sorted in alphabetical order. For example: "label1, label2, label3"',
        "labels": [
            "neutral",
            "anger",
            "anticipation",
            "disgust",
            "fear",
            "joy",
            "love",
            "optimism",
            "pessimism",
            "sadness",
            "surprise",
            "trust",
        ],
        "example_template": "Input: {example}\nOutput: {labels}",
    },
}

config["model"]["compute_confidence"] = True
```

I run the labeling agent and try to save it but I receive a recursion error and my csv file is empty.

When I set `config["model"]["compute_confidence"] = False` then the code works as it should

**Expected behavior**

I expected to receive a confidence score for each resulting label, similar to the single-class classification task.

**Additional context**

A shortened version of the error message:
```
`  
Traceback (most recent call last):
  File "Autolabel\test_twitter_emotions.py", line 56, in <module>
    ds.save("test.csv")
  File "Autolabel\venv\lib\site-packages\autolabel\dataset\dataset.py", line 172, in save
    self.df.to_csv(
  File "Autolabel\venv\lib\site-packages\pandas\core\generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "Autolabel\venv\lib\site-packages\pandas\io\formats\format.py", line 1152, in to_csv
    csv_formatter.save()
  File "Autolabel\venv\lib\site-packages\pandas\io\formats\csvs.py", line 266, in save
    self._save()
  File "Autolabel\venv\lib\site-packages\pandas\io\formats\csvs.py", line 271, in _save
    self._save_body()
  File "Autolabel\venv\lib\site-packages\pandas\io\formats\csvs.py", line 309, in _save_body
    self._save_chunk(start_i, end_i)
  File "Autolabel\venv\lib\site-packages\pandas\io\formats\csvs.py", line 320, in _save_chunk
    libwriters.write_csv_rows(
  File "writers.pyx", line 75, in pandas._libs.writers.write_csv_rows
  File "pydantic\utils.py", line 406, in pydantic.utils.Representation.__str__
  File "pydantic\utils.py", line 388, in genexpr
  File "pydantic\utils.py", line 388, in genexpr
  File "pydantic\utils.py", line 409, in pydantic.utils.Representation.__repr__
  [... many repetitions of the message above...]
  File "pydantic\utils.py", line 388, in genexpr
  File "pydantic\utils.py", line 388, in genexpr
  File "pydantic\utils.py", line 409, in pydantic.utils.Representation.__repr__
RecursionError: maximum recursion depth exceeded while calling a Python object

Process finished with exit code 1
`
```

The complete code, that I used:
```
`from autolabel import LabelingAgent, AutolabelDataset
import os
import pandas as pd


pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

os.environ["REFUEL_API_KEY"]="sk-XX" 

config = {
    "task_name": "EmotionClassification",
    "task_type": "multilabel_classification",
    "dataset": {"label_column": "labels", "label_separator": ", ", "delimiter": ","},
    "model": {"provider": "refuel", "name": "refuel-llm"},
    "prompt": {
        "task_guidelines": "You are an expert at classifying tweets as neutral or one or more of the given emotions that best represent the mental state of the poster.\nYour job is to correctly label the provided input example into one or more of the following categories:\n{labels}",
        "output_guidelines": 'You will return the answer as a comma separated list of labels sorted in alphabetical order. For example: "label1, label2, label3"',
        "labels": [
            "neutral",
            "anger",
            "anticipation",
            "disgust",
            "fear",
            "joy",
            "love",
            "optimism",
            "pessimism",
            "sadness",
            "surprise",
            "trust",
        ],
        "example_template": "Input: {example}\nOutput: {labels}",
    },
}

config["model"]["compute_confidence"] = True

agent = LabelingAgent(config=config)

ds = AutolabelDataset("seed_multilabel.csv", config=config)
agent.plan(ds)

ds = agent.run(ds, max_items=10)

ds.save("test.csv")`
```

**Comment by rishabh-bhargava** [comment]
@suz4n99 - saw that you closed this issue. Were you able to resolve it, and if so, what was the resolution?

**Comment by suz4n99** [comment]
Hi Rishabh,

I closed this issue because somehow it worked a few days later. I changed
nothing in my code but I am happy that it worked 😅.

Best wishes,
Suzan

Rishabh Bhargava ***@***.***> schrieb am Sa. 25. Nov. 2023 um
23:31:
